---
name: TeleportGuard
version: 1.1.2
main: J0k3rrWild\TeleportGuard\Main
website: https://github.com/J0k3rrWild
api: 4.0.0
permissions:
 teleportguard.tp:
  default: op
  description: Teleport to player immediately
 teleportguard.warp.set:
  default: op
  description: Set a warp
 teleportguard.warp.list:
  default: op
  description: Allow list warps
 teleportguard.admin:
  default: op
  description: Gives all plugin permissions


...
