---
name: TeleportGuard
version: 0.0.1
main: J0k3rrWild\TeleportGuard\Main
website: https://github.com/J0k3rrWild
api: 3.26.3

commands:
  tp:
  permission: teleportguard.command.tp
  description: Teleportuje do celu
  usage: /tp <player> | /tp <player> <target>| /tp <x> <y> <z> | /tp <player> <x> <y> <z>
  aliases: [tp, teleport]

...
